adminUser: admin
adminPassword: admin

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.monitoring.svc.cluster.local
        isDefault: true

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'ecommerce'
        orgId: 1
        folder: 'Ecommerce Monitoring'
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/ecommerce

dashboards:
  ecommerce:
    ecommerce-dashboard:
      file: /var/lib/grafana/dashboards/ecommerce/ecommerce-dashboard.json

sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard

