apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  namespace: monitoring
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'flask-microservices'
        static_configs:
          - targets:
              - user-service.default.svc.cluster.local:80
              - product-service.default.svc.cluster.local:80
              - order-service.default.svc.cluster.local:80


